format = """
$directory\
$git_branch\
$cmd_duration\
$character"""

[character]
success_symbol = "ğŸµ [Î»](bold green)"
error_symbol = "ğŸ™ˆ [Î»](bold red)"

[package]
disabled = true

[cmd_duration]
min_time = 100
